name: Workflow
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get
          
      # Generate all mock files    
      - name: Generate mocks
        run: flutter pub run build_runner build

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      # - name: Analyze project source
      #    run: flutter analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test --coverage
      
      # Check test coverage
      - name: Check coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "./coverage/lcov.info"
          min_coverage: 90
          
      - name: Codecov report
        uses: codecov/codecov-action@v2
      
        
