name: Flutter
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get
          
      # Generate all mock files    
      - name: Generate mocks
        run: flutter pub run build_runner build

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test --coverage
      
      # Check test coverage
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "./coverage/lcov.info"
          min_coverage: 90
      
        
